version: "3.9"
services:
  worker:
    build: ./worker
    command: pnpm dev
    env_file: ./worker/.env
    volumes:
      - ./worker:/app
    working_dir: /app
  api:
    build: ./api
    command: pnpm dev
    env_file: ./api/.env
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app
    working_dir: /app